export enum UserRole {
  CITIZEN = 'CITIZEN',
  FIELD_WORKER = 'FIELD_WORKER',
  WARD_OFFICER = 'WARD_OFFICER',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  ZONAL_OFFICER = 'ZONAL_OFFICER',
  COMMISSIONER = 'COMMISSIONER',
  CITY_ADMIN = 'CITY_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export enum IncidentStatus {
  REPORTED = 'REPORTED',
  AI_REVIEW = 'AI_REVIEW',
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLUTION_SUBMITTED = 'RESOLUTION_SUBMITTED',
  AI_VERIFICATION = 'AI_VERIFICATION',
  CITIZEN_CONFIRMATION = 'CITIZEN_CONFIRMATION',
  RESOLVED = 'RESOLVED',
  DUPLICATE = 'DUPLICATE',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  DISPUTED = 'DISPUTED',
  REOPENED = 'REOPENED'
}

export enum IncidentCategory {
  POTHOLE = 'POTHOLE',
  GARBAGE = 'GARBAGE',
  STREETLIGHT = 'STREETLIGHT',
  DRAINAGE = 'DRAINAGE',
  WATER_LEAKAGE = 'WATER_LEAKAGE',
  ROAD_DAMAGE = 'ROAD_DAMAGE',
  TRAFFIC_SIGNAL = 'TRAFFIC_SIGNAL',
  PUBLIC_TOILET = 'PUBLIC_TOILET',
  ILLEGAL_DUMPING = 'ILLEGAL_DUMPING',
  WATERLOGGING = 'WATERLOGGING',
  OTHER = 'OTHER'
}
