import { Router, Request, Response } from 'express';
import { UserRole } from '@prisma/client';
import { prisma } from '../db';
import { AuthenticatedRequest, authenticateJWT, requireRole } from '../middleware/auth';
import { integrationSecret, verifyIntegrationSignature } from '../services/integrationSecurity';

const router = Router();
const officials = [UserRole.CITY_ADMIN, UserRole.COMMISSIONER, UserRole.SUPER_ADMIN];
const gate = (res: Response) => { if (process.env.NODE_ENV !== 'production' || process.env.CIVIQUE_INTEGRATIONS_ENABLED === 'true') return true; res.status(404).json({ success: false, error: { code: 'INTEGRATIONS_DISABLED', message: 'Government integrations are not enabled for this environment.' } }); return false; };

router.post('/webhooks/:provider', async (req: Request, res: Response) => {
  if (!gate(res)) return;
  const provider = req.params.provider.trim().toLowerCase(); const eventId = String(req.headers['x-civique-event-id'] || '').trim(); const eventType = String(req.headers['x-civique-event-type'] || 'external.update').trim(); const timestamp = String(req.headers['x-civique-timestamp'] || '').trim(); const signature = String(req.headers['x-civique-signature'] || '').trim(); const sequenceHeader = String(req.headers['x-civique-sequence'] || '').trim(); const eventSequence = sequenceHeader && /^\d+$/.test(sequenceHeader) ? BigInt(sequenceHeader) : null; const secret = integrationSecret(provider);
  if (!eventId || !timestamp || !signature || !secret) return res.status(401).json({ success: false, error: { code: 'WEBHOOK_SIGNATURE_REQUIRED', message: 'A signed integration webhook is required.' } });
  const payload = JSON.stringify(req.body ?? {}); if (!verifyIntegrationSignature(payload, signature, secret, timestamp)) return res.status(401).json({ success: false, error: { code: 'WEBHOOK_SIGNATURE_INVALID', message: 'Webhook signature is invalid or expired.' } });
  const payloadHash = require('crypto').createHash('sha256').update(payload).digest('hex');
  try { const result = await prisma.$transaction(async (tx) => { if (eventSequence !== null) { const latest = await tx.$queryRawUnsafe<any[]>('SELECT event_sequence "eventSequence" FROM integration_inbox_events WHERE provider=$1 AND event_sequence IS NOT NULL ORDER BY event_sequence DESC LIMIT 1', provider); if (latest[0] && BigInt(latest[0].eventSequence) >= eventSequence) { await tx.$executeRaw`INSERT INTO integration_inbox_events (provider,event_id,event_type,event_sequence,payload_hash,payload,status,error) VALUES (${provider},${eventId},${eventType},${eventSequence},${payloadHash},${payload}::jsonb,'REJECTED_ORDER','OUT_OF_ORDER') ON CONFLICT (provider,event_id) DO NOTHING`; return { outOfOrder: true }; } } const inserted = await tx.$queryRawUnsafe<any[]>('INSERT INTO integration_inbox_events (provider,event_id,event_type,event_sequence,payload_hash,payload) VALUES ($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT (provider,event_id) DO NOTHING RETURNING id', provider, eventId, eventType, eventSequence, payloadHash, payload); if (!inserted[0]) return { duplicate: true }; const externalId = typeof req.body?.externalId === 'string' ? req.body.externalId : null; if (externalId) await tx.$executeRaw`INSERT INTO external_references (provider,external_id,report_id,incident_id,external_status,payload_hash,metadata) VALUES (${provider},${externalId},${req.body?.reportId || null}::uuid,${req.body?.incidentId || null}::uuid,${req.body?.status || null},${payloadHash},${JSON.stringify(req.body?.metadata || {})}::jsonb) ON CONFLICT (provider,external_id) DO UPDATE SET external_status=EXCLUDED.external_status,payload_hash=EXCLUDED.payload_hash,last_seen_at=NOW(),metadata=EXCLUDED.metadata`; await tx.$executeRaw`UPDATE integration_inbox_events SET status='PROCESSED',processed_at=NOW() WHERE id=${inserted[0].id}::uuid`; return { duplicate: false, id: inserted[0].id }; }); if ((result as any).outOfOrder) return res.status(409).json({ success: false, error: { code: 'WEBHOOK_OUT_OF_ORDER', message: 'Event sequence is older than the last accepted event.' } }); return res.status((result as any).duplicate ? 200 : 202).json({ success: true, data: { accepted: true, duplicate: (result as any).duplicate || false, inboxEventId: (result as any).id || null } }); } catch (error) { console.error(JSON.stringify({ module: 'integrations', operation: 'webhook', provider, status: 'ERROR', errorType: error instanceof Error ? error.name : 'UnknownError' })); return res.status(503).json({ success: false, error: { code: 'WEBHOOK_RETRY', message: 'Webhook was not persisted; retry with the same event ID.' } }); }
});

router.get('/adapters', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const actor = await prisma.user.findUnique({ where: { id: req.user!.id }, select: { role: true, cityId: true } }); const rows = await prisma.$queryRawUnsafe<any[]>(actor?.role === UserRole.SUPER_ADMIN ? 'SELECT id,"city_id" "cityId",provider,channel,status,config,"created_at" "createdAt","updated_at" "updatedAt" FROM integration_adapters ORDER BY provider,channel' : 'SELECT id,"city_id" "cityId",provider,channel,status,config,"created_at" "createdAt","updated_at" "updatedAt" FROM integration_adapters WHERE city_id=$1::uuid ORDER BY provider,channel', ...(actor?.role === UserRole.SUPER_ADMIN ? [] : [actor?.cityId])); return res.json({ success: true, data: { adapters: rows } }); });
router.post('/adapters', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const provider = typeof req.body?.provider === 'string' ? req.body.provider.trim().toLowerCase() : ''; const channel = typeof req.body?.channel === 'string' ? req.body.channel.trim().toUpperCase() : ''; const cityId = typeof req.body?.cityId === 'string' ? req.body.cityId : ''; if (!provider || !channel || !cityId) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Provider, channel, and city are required.' } }); const actor = await prisma.user.findUnique({ where: { id: req.user!.id }, select: { role: true, cityId: true } }); if (actor?.role !== UserRole.SUPER_ADMIN && actor?.cityId !== cityId) return res.status(403).json({ success: false, error: { code: 'SCOPE_DENIED', message: 'You cannot configure another city.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('INSERT INTO integration_adapters (city_id,provider,channel,status,config) VALUES ($1::uuid,$2,$3,\'DISABLED\',$4::jsonb) ON CONFLICT (city_id,provider,channel) DO UPDATE SET config=EXCLUDED.config,updated_at=NOW() RETURNING id,"city_id" "cityId",provider,channel,status', cityId, provider, channel, JSON.stringify(req.body?.config || {})); return res.status(201).json({ success: true, data: { adapter: rows[0], activation: 'DISABLED_UNTIL_APPROVED' } }); });
router.patch('/adapters/:id/status', authenticateJWT, requireRole([UserRole.SUPER_ADMIN]), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const status = typeof req.body?.status === 'string' ? req.body.status.toUpperCase() : ''; const approvalReference = typeof req.body?.approvalReference === 'string' ? req.body.approvalReference.trim() : ''; if (!['ACTIVE', 'PAUSED', 'DISABLED'].includes(status)) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Adapter status is invalid.' } }); if (status === 'ACTIVE' && (!approvalReference || !process.env.CIVIQUE_INTEGRATION_APPROVAL_TOKEN || approvalReference !== process.env.CIVIQUE_INTEGRATION_APPROVAL_TOKEN)) return res.status(403).json({ success: false, error: { code: 'APPROVAL_REQUIRED', message: 'A matching formal authority approval reference is required to activate an adapter.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('UPDATE integration_adapters SET status=$1,updated_at=NOW() WHERE id=$2::uuid RETURNING id,provider,channel,status,updated_at "updatedAt"', status, req.params.id); if (!rows[0]) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Adapter not found.' } }); return res.json({ success: true, data: { adapter: rows[0] } }); });
router.get('/references', authenticateJWT, requireRole(officials), async (_req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('SELECT id,provider,external_id "externalId",report_id "reportId",incident_id "incidentId",external_status "externalStatus",last_seen_at "lastSeenAt",metadata FROM external_references ORDER BY last_seen_at DESC LIMIT 200'); return res.json({ success: true, data: { references: rows } }); });
router.post('/references', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const provider = typeof req.body?.provider === 'string' ? req.body.provider.trim().toLowerCase() : ''; const externalId = typeof req.body?.externalId === 'string' ? req.body.externalId.trim() : ''; const reportId = typeof req.body?.reportId === 'string' ? req.body.reportId : null; const incidentId = typeof req.body?.incidentId === 'string' ? req.body.incidentId : null; if (!provider || !externalId || (!reportId && !incidentId)) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Provider, external ID, and a Report or Incident target are required.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('INSERT INTO external_references (provider,external_id,report_id,incident_id,external_status,payload_hash,metadata) VALUES ($1,$2,$3::uuid,$4::uuid,$5,$6,$7::jsonb) ON CONFLICT (provider,external_id) DO UPDATE SET report_id=COALESCE(EXCLUDED.report_id,external_references.report_id),incident_id=COALESCE(EXCLUDED.incident_id,external_references.incident_id),metadata=EXCLUDED.metadata,last_seen_at=NOW() RETURNING id,provider,external_id "externalId",report_id "reportId",incident_id "incidentId"', provider, externalId, reportId, incidentId, req.body?.externalStatus || null, 'manual-mapping', JSON.stringify({ source: 'operator' })); return res.status(201).json({ success: true, data: { reference: rows[0] } }); });
router.post('/deliveries', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const provider = typeof req.body?.provider === 'string' ? req.body.provider.trim().toLowerCase() : ''; const eventType = typeof req.body?.eventType === 'string' ? req.body.eventType.trim() : ''; const aggregateId = typeof req.body?.aggregateId === 'string' ? req.body.aggregateId : ''; const idempotencyKey = typeof req.body?.idempotencyKey === 'string' ? req.body.idempotencyKey.trim() : ''; if (!provider || !eventType || !aggregateId || !idempotencyKey) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Provider, event type, aggregate, and idempotency key are required.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('INSERT INTO integration_deliveries (provider,event_type,aggregate_id,idempotency_key,payload) VALUES ($1,$2,$3::uuid,$4,$5::jsonb) ON CONFLICT (idempotency_key) DO UPDATE SET updated_at=integration_deliveries.updated_at RETURNING id,status,attempts,"next_attempt_at" "nextAttemptAt"', provider, eventType, aggregateId, idempotencyKey, JSON.stringify(req.body?.payload || {})); return res.status(202).json({ success: true, data: { delivery: rows[0] } }); });
router.post('/deliveries/:id/receipt', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const status = typeof req.body?.status === 'string' ? req.body.status.toUpperCase() : ''; if (!['DELIVERED', 'FAILED', 'RETRYING'].includes(status)) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Receipt status must be DELIVERED, FAILED, or RETRYING.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('UPDATE integration_deliveries SET status=$1,attempts=attempts+1,response_code=$2,response_body=$3,external_id=$4,delivered_at=CASE WHEN $1=\'DELIVERED\' THEN NOW() ELSE delivered_at END,updated_at=NOW() WHERE id=$5::uuid RETURNING id,status,attempts', status, req.body?.responseCode || null, typeof req.body?.responseBody === 'string' ? req.body.responseBody.slice(0, 1000) : null, req.body?.externalId || null, req.params.id); if (!rows[0]) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Delivery not found.' } }); return res.json({ success: true, data: { delivery: rows[0] } }); });
router.post('/deliveries/:id/retry', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('UPDATE integration_deliveries SET status=\'PENDING\',next_attempt_at=NOW(),updated_at=NOW() WHERE id=$1::uuid AND status IN (\'FAILED\',\'RETRYING\') AND attempts < 10 RETURNING id,status,attempts,"next_attempt_at" "nextAttemptAt"', req.params.id); if (!rows[0]) return res.status(409).json({ success: false, error: { code: 'RETRY_NOT_ALLOWED', message: 'Delivery is not retryable or has exhausted attempts.' } }); return res.json({ success: true, data: { delivery: rows[0] } }); });
router.get('/deliveries', authenticateJWT, requireRole(officials), async (_req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('SELECT id,provider,event_type "eventType",aggregate_id "aggregateId",status,attempts,response_code "responseCode",next_attempt_at "nextAttemptAt",created_at "createdAt" FROM integration_deliveries ORDER BY created_at DESC LIMIT 200'); return res.json({ success: true, data: { deliveries: rows } }); });
router.get('/inbox', authenticateJWT, requireRole(officials), async (_req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('SELECT id,provider,event_id "eventId",event_type "eventType",event_sequence "eventSequence",status,received_at "receivedAt",processed_at "processedAt",error FROM integration_inbox_events ORDER BY received_at DESC LIMIT 200'); return res.json({ success: true, data: { events: rows } }); });
router.get('/conflicts', authenticateJWT, requireRole(officials), async (_req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('SELECT c.id,c.external_reference_id "externalReferenceId",c.kind,c.details,c.status,c.created_at "createdAt",r.provider,r.external_id "externalId" FROM integration_conflicts c JOIN external_references r ON r.id=c.external_reference_id WHERE c.status=\'OPEN\' ORDER BY c.created_at ASC LIMIT 200'); return res.json({ success: true, data: { conflicts: rows } }); });
router.post('/conflicts/:id/resolve', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!gate(res)) return; const resolution = typeof req.body?.resolution === 'string' ? req.body.resolution.trim().slice(0, 500) : ''; if (resolution.length < 5) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'A resolution note is required.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('UPDATE integration_conflicts SET status=\'RESOLVED\',details=details || jsonb_build_object(\'resolution\',$1::text),resolved_by=$2::uuid,resolved_at=NOW() WHERE id=$3::uuid AND status=\'OPEN\' RETURNING id,status,resolved_at "resolvedAt"', resolution, req.user!.id, req.params.id); if (!rows[0]) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Open integration conflict not found.' } }); return res.json({ success: true, data: { conflict: rows[0] } }); });

export default router;
