import { Router, Request, Response } from 'express';
import { IncidentStatus, UserRole } from '@prisma/client';
import { prisma } from '../db';
import { AuthenticatedRequest, authenticateJWT, requireRole } from '../middleware/auth';
import { logIncidentChange } from '../utils/audit';
import { incidentScope } from '../utils/scope';

const router = Router();
const citizens = [UserRole.CITIZEN];
const encodeCursor = (date: Date, id: string) => Buffer.from(`${date.toISOString()}|${id}`).toString('base64url');
const decodeCursor = (value: string) => { const [date, id] = Buffer.from(value, 'base64url').toString().split('|'); const parsed = new Date(date); return Number.isNaN(parsed.getTime()) || !id ? null : { date: parsed, id }; };
const redact = (value: string | null) => (value || 'Civic issue reported by a resident.').replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g, '[contact hidden]').replace(/\+?\d[\d\s-]{7,}\d/g, '[contact hidden]').slice(0, 600);
const generalized = (value: number) => Math.round(value * 100) / 100;
const officials = [UserRole.WARD_OFFICER, UserRole.DEPARTMENT_HEAD, UserRole.ZONAL_OFFICER, UserRole.COMMISSIONER, UserRole.CITY_ADMIN, UserRole.SUPER_ADMIN];
const socioEnabled = () => process.env.NODE_ENV !== 'production' || process.env.CIVIQUE_SOCIO_ENABLED === 'true';
const ensureEnabled = (res: Response) => {
  if (socioEnabled()) return true;
  res.status(404).json({ success: false, error: { code: 'SOCIO_DISABLED', message: 'Civique Socio is not enabled for this environment.' } });
  return false;
};
const postSelect = `id,report_id "reportId",incident_id "incidentId",alias,redacted_text "text",generalized_latitude "latitude",generalized_longitude "longitude",category,status,publication_version "publicationVersion",created_at "createdAt",updated_at "updatedAt"`;

router.get('/', async (req: Request, res: Response) => {
  if (!ensureEnabled(res)) return;
  const limit = Math.min(Math.max(Number(req.query.limit) || 20, 1), 50); const cursor = typeof req.query.cursor === 'string' ? decodeCursor(req.query.cursor) : null; const category = typeof req.query.category === 'string' ? req.query.category.toUpperCase() : null; const status = typeof req.query.status === 'string' ? req.query.status.toUpperCase() : null; const scope = typeof req.query.scope === 'string' ? req.query.scope : null;
  const clauses = ['visibility=\'PUBLIC\'', 'revoked_at IS NULL']; const params: any[] = []; if (category) { params.push(category); clauses.push(`category=$${params.length}`); } if (status) { params.push(status); clauses.push(`status=$${params.length}`); } if (scope?.startsWith('ward:')) { params.push(scope.slice(5)); clauses.push(`incident_id IN (SELECT id FROM incidents WHERE ward_id=$${params.length}::uuid)`); } if (cursor) { params.push(cursor.date, cursor.id); clauses.push(`(created_at,id)<($${params.length - 1},$${params.length}::uuid)`); } params.push(limit + 1);
  const rows = await prisma.$queryRawUnsafe<any[]>(`SELECT id,report_id "reportId",incident_id "incidentId",alias,redacted_text "text",generalized_latitude "latitude",generalized_longitude "longitude",category,status,publication_version "publicationVersion",created_at "createdAt" FROM socio_posts WHERE ${clauses.join(' AND ')} ORDER BY created_at DESC,id DESC LIMIT $${params.length}`, ...params); const hasMore = rows.length > limit; const page = rows.slice(0, limit); return res.json({ success: true, data: { posts: page, pagination: { hasMore, nextCursor: hasMore ? encodeCursor(page[page.length - 1].createdAt, page[page.length - 1].id) : null }, rankingVersion: 'm22-locality-relevance-recency-v1' } });
});

router.get('/posts/:id', async (req: Request, res: Response) => { if (!ensureEnabled(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>(`SELECT ${postSelect} FROM socio_posts WHERE id=$1::uuid AND visibility='PUBLIC' AND revoked_at IS NULL`, req.params.id); if (!rows[0]) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Socio post not found.' } }); const updates = await prisma.$queryRawUnsafe<any[]>('SELECT id,status,message,created_at "createdAt" FROM socio_post_updates WHERE post_id=$1::uuid ORDER BY created_at ASC,id ASC', req.params.id); const counts = await prisma.$queryRawUnsafe<any[]>(`SELECT (SELECT COUNT(*)::int FROM socio_reactions WHERE post_id=$1::uuid) supports,(SELECT COUNT(*)::int FROM socio_corroborations WHERE post_id=$1::uuid AND eligibility_status='VERIFIED') corroborations,(SELECT COUNT(*)::int FROM socio_comments WHERE post_id=$1::uuid AND status='ACTIVE') comments`, req.params.id); return res.json({ success: true, data: { post: rows[0], updates, engagement: counts[0] || { supports: 0, corroborations: 0, comments: 0 }, communityRules: { authenticatedOnly: true, aliasesOnly: true, noContactDetails: true, noPopularityPriority: true } } }); });

router.post('/preview', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => {
  if (!ensureEnabled(res)) return;
  const reportId = typeof req.body?.reportId === 'string' ? req.body.reportId : ''; const consentVersion = typeof req.body?.consentVersion === 'string' ? req.body.consentVersion.trim() : '';
  if (!reportId || !consentVersion) return res.status(400).json({ success: false, error: { code: 'CONSENT_REQUIRED', message: 'Report and consent version are required.' } });
  const report = await prisma.report.findFirst({ where: { id: reportId, submitterRef: req.user!.id, incidentId: { not: null } }, include: { incident: true } });
  if (!report?.incident) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Owned report with an Incident is required.' } });
  return res.json({ success: true, data: { preview: { text: redact(report.description), generalizedLatitude: generalized(report.incident.latitude), generalizedLongitude: generalized(report.incident.longitude), category: report.incident.category, status: report.incident.status, consentVersion }, privacy: { exactLocationHidden: true, evidenceHidden: true, contactDetailsRedacted: true } } });
});

router.post('/publish', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => {
  if (!ensureEnabled(res)) return;
  const reportId = typeof req.body?.reportId === 'string' ? req.body.reportId : ''; const consentVersion = typeof req.body?.consentVersion === 'string' ? req.body.consentVersion.trim() : ''; const alias = typeof req.body?.alias === 'string' ? req.body.alias.trim().replace(/[^A-Za-z0-9 _-]/g, '').slice(0, 40) : '';
  if (!reportId || !consentVersion || alias.length < 3) return res.status(400).json({ success: false, error: { code: 'CONSENT_REQUIRED', message: 'Report, consent version, and a public alias are required.' } });
  const report = await prisma.report.findFirst({ where: { id: reportId, submitterRef: req.user!.id, incidentId: { not: null } }, include: { incident: true } }); const incident = report?.incident; if (!report || !incident) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Owned report with an Incident is required.' } });
  try { const result = await prisma.$transaction(async (tx) => { await tx.$executeRaw`INSERT INTO socio_aliases (user_id,alias) VALUES (${req.user!.id}::uuid,${alias}) ON CONFLICT (user_id) DO UPDATE SET alias=EXCLUDED.alias,updated_at=NOW()`; const rows = await tx.$queryRawUnsafe<any[]>('INSERT INTO socio_posts (report_id,incident_id,author_id,alias,consent_version,redacted_text,generalized_latitude,generalized_longitude,category,status) VALUES ($1::uuid,$2::uuid,$3::uuid,$4,$5,$6,$7,$8,$9,$10) RETURNING id', report.id, incident.id, req.user!.id, alias, consentVersion, redact(report.description), generalized(incident.latitude), generalized(incident.longitude), incident.category, incident.status); await tx.$executeRaw`INSERT INTO socio_publication_consents (post_id,user_id,consent_version,action) VALUES (${rows[0].id}::uuid,${req.user!.id}::uuid,${consentVersion},'PUBLISHED')`; await logIncidentChange(tx, incident.id, 'SOCIO_PUBLICATION_OPT_IN', req.user!.id, { postId: rows[0].id, consentVersion }); return rows[0]; }); return res.status(201).json({ success: true, data: { post: result } }); } catch (error: any) { return res.status(409).json({ success: false, error: { code: 'PUBLICATION_CONFLICT', message: error.message || 'Report is already published or cannot be published.' } }); }
});

router.post('/posts/:id/revoke', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const consentVersion = typeof req.body?.consentVersion === 'string' && req.body.consentVersion.trim() ? req.body.consentVersion.trim() : 'socio-v1'; const result = await prisma.$transaction(async (tx) => { const rows = await tx.$queryRawUnsafe<any[]>('UPDATE socio_posts SET visibility=\'REVOKED\',revoked_at=NOW(),updated_at=NOW() WHERE id=$1::uuid AND author_id=$2::uuid AND revoked_at IS NULL RETURNING incident_id "incidentId"', req.params.id, req.user!.id); if (!rows[0]) return null; await tx.$executeRaw`INSERT INTO socio_publication_consents (post_id,user_id,consent_version,action) VALUES (${req.params.id}::uuid,${req.user!.id}::uuid,${consentVersion},'REVOKED')`; await logIncidentChange(tx, rows[0].incidentId, 'SOCIO_PUBLICATION_REVOKED', req.user!.id, { postId: req.params.id }); return rows[0]; }); if (!result) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Published post not found.' } }); return res.json({ success: true, data: { revoked: true, postId: req.params.id } }); });

router.post('/posts/:id/status', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const status = typeof req.body?.status === 'string' ? req.body.status.trim().toUpperCase() : ''; const message = typeof req.body?.message === 'string' ? req.body.message.trim().slice(0, 500) : ''; if (!Object.values(IncidentStatus).includes(status as IncidentStatus) || message.length < 5) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Choose a valid incident status and provide a clear update message.' } }); const actor = await prisma.user.findUnique({ where: { id: req.user!.id }, select: { id: true, role: true, cityId: true, zoneId: true, wardId: true, departmentId: true } }); if (!actor) return res.status(401).json({ success: false, error: { code: 'UNAUTHORIZED', message: 'Account not found.' } }); const post = await prisma.$queryRawUnsafe<any[]>('SELECT id,incident_id "incidentId" FROM socio_posts WHERE id=$1::uuid AND visibility=\'PUBLIC\' AND revoked_at IS NULL', req.params.id); if (!post[0]) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Published post not found.' } }); const incident = await prisma.incident.findFirst({ where: { id: post[0].incidentId, ...incidentScope(actor as any) }, select: { id: true } }); if (!incident) return res.status(404).json({ success: false, error: { code: 'SCOPE_DENIED', message: 'Post is outside your assigned scope.' } }); await prisma.$transaction(async (tx) => { await tx.$executeRaw`UPDATE socio_posts SET status=${status},updated_at=NOW(),publication_version=publication_version+1 WHERE id=${req.params.id}::uuid`; await tx.$executeRaw`INSERT INTO socio_post_updates (post_id,status,message,actor_id) VALUES (${req.params.id}::uuid,${status},${message},${req.user!.id}::uuid)`; await logIncidentChange(tx, incident.id, 'SOCIO_STATUS_UPDATE', req.user!.id, { postId: req.params.id, status }); }); return res.json({ success: true, data: { updated: true, postId: req.params.id, status } }); });

router.post('/follows', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const scopeType = typeof req.body?.scopeType === 'string' ? req.body.scopeType.toUpperCase() : ''; const scopeKey = typeof req.body?.scopeKey === 'string' ? req.body.scopeKey.trim() : ''; if (!['WARD', 'CATEGORY', 'STATUS'].includes(scopeType) || !scopeKey) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'A valid follow scope is required.' } }); await prisma.$executeRaw`INSERT INTO socio_follows (user_id,scope_type,scope_key) VALUES (${req.user!.id}::uuid,${scopeType},${scopeKey}) ON CONFLICT DO NOTHING`; return res.status(201).json({ success: true, data: { following: true, scopeType, scopeKey } }); });
router.delete('/follows/:scopeType/:scopeKey', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; await prisma.$executeRaw`DELETE FROM socio_follows WHERE user_id=${req.user!.id}::uuid AND scope_type=${req.params.scopeType.toUpperCase()} AND scope_key=${req.params.scopeKey}`; return res.json({ success: true, data: { following: false } }); });
router.post('/posts/:id/save', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; await prisma.$executeRaw`INSERT INTO socio_saves (user_id,post_id) VALUES (${req.user!.id}::uuid,${req.params.id}::uuid) ON CONFLICT DO NOTHING`; return res.status(201).json({ success: true, data: { saved: true } }); });
router.delete('/posts/:id/save', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; await prisma.$executeRaw`DELETE FROM socio_saves WHERE user_id=${req.user!.id}::uuid AND post_id=${req.params.id}::uuid`; return res.json({ success: true, data: { saved: false } }); });

const activePost = async (id: string) => (await prisma.$queryRawUnsafe<any[]>('SELECT id,author_id "authorId",incident_id "incidentId",comments_locked "commentsLocked" FROM socio_posts WHERE id=$1::uuid AND visibility=\'PUBLIC\' AND revoked_at IS NULL', id))[0];
const aliasFor = async (userId: string) => (await prisma.$queryRawUnsafe<any[]>('SELECT alias FROM socio_aliases WHERE user_id=$1::uuid', userId))[0]?.alias || 'Civique resident';
const blockedBy = async (userId: string, targetId: string) => Boolean((await prisma.$queryRawUnsafe<any[]>('SELECT 1 FROM socio_user_controls WHERE user_id=$1::uuid AND target_user_id=$2::uuid AND kind=\'BLOCK\'', userId, targetId))[0]);

router.post('/posts/:id/reactions', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const post = await activePost(req.params.id); if (!post) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Published post not found.' } }); if (await blockedBy(req.user!.id, post.authorId)) return res.status(403).json({ success: false, error: { code: 'BLOCKED', message: 'This interaction is unavailable.' } }); await prisma.$executeRaw`INSERT INTO socio_reactions (post_id,user_id,kind) VALUES (${req.params.id}::uuid,${req.user!.id}::uuid,'SUPPORT') ON CONFLICT (post_id,user_id) DO NOTHING`; const count = await prisma.$queryRawUnsafe<any[]>('SELECT COUNT(*)::int count FROM socio_reactions WHERE post_id=$1::uuid', req.params.id); return res.status(201).json({ success: true, data: { supported: true, count: count[0].count } }); });
router.delete('/posts/:id/reactions', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; await prisma.$executeRaw`DELETE FROM socio_reactions WHERE post_id=${req.params.id}::uuid AND user_id=${req.user!.id}::uuid`; const count = await prisma.$queryRawUnsafe<any[]>('SELECT COUNT(*)::int count FROM socio_reactions WHERE post_id=$1::uuid', req.params.id); return res.json({ success: true, data: { supported: false, count: count[0].count } }); });
router.post('/posts/:id/corroborations', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const post = await activePost(req.params.id); if (!post) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Published post not found.' } }); if (post.authorId === req.user!.id) return res.status(400).json({ success: false, error: { code: 'SELF_CORROBORATION', message: 'You cannot corroborate your own report.' } }); await prisma.$executeRaw`INSERT INTO socio_corroborations (post_id,user_id,kind) VALUES (${req.params.id}::uuid,${req.user!.id}::uuid,'AFFECTED') ON CONFLICT DO NOTHING`; return res.status(201).json({ success: true, data: { corroborated: true, eligibilityStatus: 'PENDING' } }); });
router.delete('/posts/:id/corroborations', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; await prisma.$executeRaw`DELETE FROM socio_corroborations WHERE post_id=${req.params.id}::uuid AND user_id=${req.user!.id}::uuid`; return res.json({ success: true, data: { corroborated: false } }); });
router.get('/posts/:id/comments', async (req: Request, res: Response) => { if (!ensureEnabled(res)) return; const post = await activePost(req.params.id); if (!post) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Published post not found.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('SELECT id,"parent_id" "parentId",alias,body,status,revision,"created_at" "createdAt","updated_at" "updatedAt" FROM socio_comments WHERE post_id=$1::uuid AND status=\'ACTIVE\' ORDER BY created_at ASC,id ASC LIMIT 100', req.params.id); return res.json({ success: true, data: { comments: rows } }); });
router.post('/posts/:id/comments', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const post = await activePost(req.params.id); const body = typeof req.body?.body === 'string' ? req.body.body.trim() : ''; const parentId = typeof req.body?.parentId === 'string' ? req.body.parentId : null; if (!post) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Published post not found.' } }); if (post.commentsLocked) return res.status(423).json({ success: false, error: { code: 'COMMENTS_LOCKED', message: 'Comments are temporarily locked by moderation.' } }); if (body.length < 2 || body.length > 500) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Comments must be between 2 and 500 characters.' } }); if (await blockedBy(req.user!.id, post.authorId)) return res.status(403).json({ success: false, error: { code: 'BLOCKED', message: 'This interaction is unavailable.' } }); const recent = await prisma.$queryRawUnsafe<any[]>('SELECT COUNT(*)::int count FROM socio_comments WHERE author_id=$1::uuid AND created_at > NOW() - INTERVAL \'1 minute\'', req.user!.id); if (recent[0].count >= 5) return res.status(429).json({ success: false, error: { code: 'RATE_LIMITED', message: 'Please wait before posting another comment.' } }); if (parentId) { const parent = await prisma.$queryRawUnsafe<any[]>('SELECT id FROM socio_comments WHERE id=$1::uuid AND post_id=$2::uuid AND parent_id IS NULL AND status=\'ACTIVE\'', parentId, req.params.id); if (!parent[0]) return res.status(400).json({ success: false, error: { code: 'INVALID_THREAD', message: 'Comments can only reply one level deep.' } }); } const alias = await aliasFor(req.user!.id); const rows = await prisma.$queryRawUnsafe<any[]>('INSERT INTO socio_comments (post_id,parent_id,author_id,alias,body) VALUES ($1::uuid,$2::uuid,$3::uuid,$4,$5) RETURNING id,"parent_id" "parentId",alias,body,status,revision,"created_at" "createdAt"', req.params.id, parentId, req.user!.id, alias, body); return res.status(201).json({ success: true, data: { comment: rows[0] } }); });
router.patch('/comments/:id', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const body = typeof req.body?.body === 'string' ? req.body.body.trim() : ''; if (body.length < 2 || body.length > 500) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Comment text must be between 2 and 500 characters.' } }); const result = await prisma.$transaction(async (tx) => { const old = await tx.$queryRawUnsafe<any[]>('SELECT id,body,revision FROM socio_comments WHERE id=$1::uuid AND author_id=$2::uuid AND status=\'ACTIVE\'', req.params.id, req.user!.id); if (!old[0]) return null; await tx.$executeRaw`INSERT INTO socio_comment_revisions (comment_id,revision,body,edited_by) VALUES (${req.params.id}::uuid,${old[0].revision},${old[0].body},${req.user!.id}::uuid)`; return (await tx.$queryRawUnsafe<any[]>('UPDATE socio_comments SET body=$1,revision=revision+1,updated_at=NOW() WHERE id=$2::uuid RETURNING id,body,revision,"updated_at" "updatedAt"', body, req.params.id))[0]; }); if (!result) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Comment not found.' } }); return res.json({ success: true, data: { comment: result } }); });
router.post('/content-reports', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const postId = typeof req.body?.postId === 'string' ? req.body.postId : null; const commentId = typeof req.body?.commentId === 'string' ? req.body.commentId : null; const reason = typeof req.body?.reason === 'string' ? req.body.reason.trim().slice(0, 300) : ''; if ((!postId && !commentId) || (postId && commentId) || reason.length < 5) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Choose one target and provide a moderation reason.' } }); const target = postId ? await activePost(postId) : (await prisma.$queryRawUnsafe<any[]>('SELECT id,post_id "postId" FROM socio_comments WHERE id=$1::uuid AND status=\'ACTIVE\'', commentId))[0]; if (!target) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Content not found.' } }); try { const result = await prisma.$transaction(async (tx) => { const rows = await tx.$queryRawUnsafe<any[]>('INSERT INTO socio_content_reports (post_id,comment_id,reporter_id,reason) VALUES ($1::uuid,$2::uuid,$3::uuid,$4) RETURNING id', postId, commentId, req.user!.id, reason); const caseRows = await tx.$queryRawUnsafe<any[]>('INSERT INTO socio_moderation_cases (post_id,comment_id,content_report_id,reason) VALUES ($1::uuid,$2::uuid,$3::uuid,$4) RETURNING id,status', postId, commentId, rows[0].id, reason); return { report: rows[0], case: caseRows[0] }; }); return res.status(201).json({ success: true, data: { reportId: result.report.id, case: result.case } }); } catch (error: any) { if (error?.code === 'P2002' || error?.code === '23505') return res.status(409).json({ success: false, error: { code: 'DUPLICATE_REPORT', message: 'You already have an open report for this content.' } }); return res.status(500).json({ success: false, error: { code: 'MODERATION_REPORT_FAILED', message: 'The moderation report could not be recorded.' } }); } });
router.post('/controls', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const targetUserId = typeof req.body?.targetUserId === 'string' ? req.body.targetUserId : ''; const kind = typeof req.body?.kind === 'string' ? req.body.kind.toUpperCase() : ''; if (!targetUserId || !['BLOCK','MUTE'].includes(kind) || targetUserId === req.user!.id) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'A valid target and BLOCK or MUTE control are required.' } }); await prisma.$executeRaw`INSERT INTO socio_user_controls (user_id,target_user_id,kind) VALUES (${req.user!.id}::uuid,${targetUserId}::uuid,${kind}) ON CONFLICT DO NOTHING`; return res.status(201).json({ success: true, data: { kind, active: true } }); });
router.delete('/controls/:kind/:targetUserId', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; await prisma.$executeRaw`DELETE FROM socio_user_controls WHERE user_id=${req.user!.id}::uuid AND target_user_id=${req.params.targetUserId}::uuid AND kind=${req.params.kind.toUpperCase()}`; return res.json({ success: true, data: { active: false } }); });
router.get('/reputation/me', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>(`SELECT LEAST(100, (SELECT COUNT(*) FROM socio_corroborations WHERE user_id=$1::uuid AND eligibility_status='VERIFIED') * 2 + (SELECT COUNT(*) FROM socio_comments WHERE author_id=$1::uuid AND status='ACTIVE') + (SELECT COUNT(*) FROM socio_content_reports WHERE reporter_id=$1::uuid AND status='RESOLVED'))::int score`, req.user!.id); return res.json({ success: true, data: { score: rows[0]?.score || 0, version: 'm23-reputation-v1', purpose: 'trust-and-moderation-context-only', affectsPriority: false } }); });

router.get('/moderation/corroborations', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('SELECT c.post_id "postId",c.user_id "userId",c.eligibility_status "eligibilityStatus",c.created_at "createdAt",p.incident_id "incidentId" FROM socio_corroborations c JOIN socio_posts p ON p.id=c.post_id WHERE c.eligibility_status=\'PENDING\' AND p.visibility=\'PUBLIC\' ORDER BY c.created_at ASC LIMIT 100'); return res.json({ success: true, data: { corroborations: rows } }); });
router.post('/moderation/corroborations/:postId/:userId', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const decision = typeof req.body?.decision === 'string' ? req.body.decision.toUpperCase() : ''; if (!['VERIFIED', 'REJECTED'].includes(decision)) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Decision must be VERIFIED or REJECTED.' } }); const post = await prisma.$queryRawUnsafe<any[]>('SELECT incident_id "incidentId" FROM socio_posts WHERE id=$1::uuid AND visibility=\'PUBLIC\'', req.params.postId); if (!post[0]) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Public post not found.' } }); const actor = await prisma.user.findUnique({ where: { id: req.user!.id }, select: { id: true, role: true, cityId: true, zoneId: true, wardId: true, departmentId: true } }); if (!actor || !(await prisma.incident.findFirst({ where: { id: post[0].incidentId, ...incidentScope(actor as any) }, select: { id: true } }))) return res.status(403).json({ success: false, error: { code: 'SCOPE_DENIED', message: 'This corroboration is outside your assigned scope.' } }); const result = await prisma.$queryRawUnsafe<any[]>('UPDATE socio_corroborations SET eligibility_status=$1,reviewed_at=NOW() WHERE post_id=$2::uuid AND user_id=$3::uuid AND eligibility_status=\'PENDING\' RETURNING post_id "postId",user_id "userId",eligibility_status "eligibilityStatus"', decision, req.params.postId, req.params.userId); if (!result[0]) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Pending corroboration not found.' } }); return res.json({ success: true, data: { corroboration: result[0], priorityInput: decision === 'VERIFIED' ? 'eligible-versioned-corroboration' : 'excluded' } }); });
router.get('/moderation/appeals', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('SELECT id,case_id "caseId",appellant_id "appellantId",reason,status,created_at "createdAt" FROM socio_moderation_appeals WHERE status=\'OPEN\' ORDER BY created_at ASC LIMIT 100'); return res.json({ success: true, data: { appeals: rows } }); });
router.post('/moderation/appeals/:id/review', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const decision = typeof req.body?.decision === 'string' ? req.body.decision.toUpperCase() : ''; const reason = typeof req.body?.reason === 'string' ? req.body.reason.trim().slice(0, 500) : ''; if (!['APPROVED', 'REJECTED'].includes(decision) || reason.length < 5) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Choose an appeal decision and provide a reason.' } }); const result = await prisma.$transaction(async (tx) => { const appeal = await tx.$queryRawUnsafe<any[]>('SELECT a.id,a.case_id "caseId",c.post_id "postId" FROM socio_moderation_appeals a JOIN socio_moderation_cases c ON c.id=a.case_id WHERE a.id=$1::uuid AND a.status=\'OPEN\'', req.params.id); if (!appeal[0]) return null; await tx.$executeRaw`UPDATE socio_moderation_appeals SET status=${decision},reviewed_by=${req.user!.id}::uuid,reviewed_at=NOW() WHERE id=${req.params.id}::uuid`; await tx.$executeRaw`INSERT INTO socio_moderation_actions (case_id,action,reason,actor_id) VALUES (${appeal[0].caseId}::uuid,${decision === 'APPROVED' ? 'RESTORE' : 'APPEAL_REJECTED'},${reason},${req.user!.id}::uuid)`; if (decision === 'APPROVED' && appeal[0].postId) await tx.$executeRaw`UPDATE socio_posts SET visibility='PUBLIC',updated_at=NOW(),publication_version=publication_version+1 WHERE id=${appeal[0].postId}::uuid AND revoked_at IS NULL`; await tx.$executeRaw`UPDATE socio_moderation_cases SET status=${decision === 'APPROVED' ? 'RESOLVED' : 'DISMISSED'},updated_at=NOW() WHERE id=${appeal[0].caseId}::uuid`; return { id: req.params.id, decision }; }); if (!result) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Open appeal not found.' } }); return res.json({ success: true, data: { appeal: result } }); });

router.get('/moderation/cases', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const rows = await prisma.$queryRawUnsafe<any[]>('SELECT id,"post_id" "postId","comment_id" "commentId",status,reason,"created_at" "createdAt" FROM socio_moderation_cases WHERE status IN (\'OPEN\',\'APPEALED\') ORDER BY created_at ASC LIMIT 100'); return res.json({ success: true, data: { cases: rows } }); });
router.post('/moderation/cases/:id/actions', authenticateJWT, requireRole(officials), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const action = typeof req.body?.action === 'string' ? req.body.action.toUpperCase() : ''; const reason = typeof req.body?.reason === 'string' ? req.body.reason.trim().slice(0, 500) : ''; const allowed = ['LIMIT_VISIBILITY','REDACT','LOCK_COMMENTS','REMOVE_PROJECTION','WARN','SUSPEND','ESCALATE','DISMISS']; if (!allowed.includes(action) || reason.length < 5) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'A valid moderation action and reason are required.' } }); const result = await prisma.$transaction(async (tx) => { const cases = await tx.$queryRawUnsafe<any[]>('SELECT c.id,c.post_id "postId",c.comment_id "commentId",COALESCE(p.author_id,cm.author_id) "targetAuthorId" FROM socio_moderation_cases c LEFT JOIN socio_posts p ON p.id=c.post_id LEFT JOIN socio_comments cm ON cm.id=c.comment_id WHERE c.id=$1::uuid AND c.status IN (\'OPEN\',\'APPEALED\')', req.params.id); if (!cases[0]) return null; await tx.$executeRaw`INSERT INTO socio_moderation_actions (case_id,action,reason,actor_id) VALUES (${req.params.id}::uuid,${action},${reason},${req.user!.id}::uuid)`; if (cases[0].commentId && ['REDACT','LOCK_COMMENTS','REMOVE_PROJECTION'].includes(action)) await tx.$executeRaw`UPDATE socio_comments SET status='HIDDEN',updated_at=NOW() WHERE id=${cases[0].commentId}::uuid`; if (cases[0].postId && action === 'LOCK_COMMENTS') await tx.$executeRaw`UPDATE socio_posts SET comments_locked=TRUE,updated_at=NOW(),publication_version=publication_version+1 WHERE id=${cases[0].postId}::uuid`; if (cases[0].postId && ['REMOVE_PROJECTION','LIMIT_VISIBILITY'].includes(action)) await tx.$executeRaw`UPDATE socio_posts SET visibility='MODERATED',updated_at=NOW(),publication_version=publication_version+1 WHERE id=${cases[0].postId}::uuid`; if (action === 'SUSPEND' && cases[0].targetAuthorId) await tx.$executeRaw`UPDATE users SET active=FALSE,updated_at=NOW() WHERE id=${cases[0].targetAuthorId}::uuid AND role='CITIZEN'`; return (await tx.$queryRawUnsafe<any[]>('UPDATE socio_moderation_cases SET status=$1,updated_at=NOW() WHERE id=$2::uuid RETURNING id,status', action === 'DISMISS' ? 'DISMISSED' : 'RESOLVED', req.params.id))[0]; }); if (!result) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Moderation case not found.' } }); return res.json({ success: true, data: { case: result } }); });
router.post('/moderation/cases/:id/appeals', authenticateJWT, requireRole(citizens), async (req: AuthenticatedRequest, res: Response) => { if (!ensureEnabled(res)) return; const reason = typeof req.body?.reason === 'string' ? req.body.reason.trim().slice(0, 500) : ''; if (reason.length < 5) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'An appeal reason is required.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('INSERT INTO socio_moderation_appeals (case_id,appellant_id,reason) VALUES ($1::uuid,$2::uuid,$3) RETURNING id,status', req.params.id, req.user!.id, reason); await prisma.$executeRaw`UPDATE socio_moderation_cases SET status='APPEALED',updated_at=NOW() WHERE id=${req.params.id}::uuid`; return res.status(201).json({ success: true, data: { appeal: rows[0] } }); });

export default router;
