import { Router, Request, Response } from 'express';
import { UserRole } from '@prisma/client';
import { prisma } from '../db';
import { AuthenticatedRequest, authenticateJWT, requireRole } from '../middleware/auth';

const router = Router();
const admins = [UserRole.CITY_ADMIN, UserRole.COMMISSIONER, UserRole.SUPER_ADMIN];
const superOnly = [UserRole.SUPER_ADMIN];
const publicFlags = new Set(['SOCIO_ENABLED', 'PUBLIC_MAP_ENABLED', 'REPORTING_ENABLED', 'PREDICTIONS_ENABLED']);

router.get('/public/:slug', async (req: Request, res: Response) => { const rows = await prisma.$queryRawUnsafe<any[]>('SELECT city_id "cityId",slug,"display_name" "displayName",timezone,default_locale "defaultLocale",data_residency "dataResidency",branding FROM tenant_settings ts JOIN cities c ON c.id=ts.city_id WHERE ts.slug=$1 AND c.active=true', req.params.slug); if (!rows[0]) return res.status(404).json({ success: false, error: { code: 'TENANT_NOT_FOUND', message: 'City configuration not found.' } }); const flags = await prisma.$queryRawUnsafe<any[]>('SELECT key,enabled,rollout_percent "rolloutPercent" FROM tenant_feature_flags WHERE city_id=$1::uuid AND key=ANY($2::text[])', rows[0].cityId, [...publicFlags]); return res.json({ success: true, data: { tenant: rows[0], features: flags } }); });

router.get('/', authenticateJWT, requireRole(admins), async (req: AuthenticatedRequest, res: Response) => { const actor = await prisma.user.findUnique({ where: { id: req.user!.id }, select: { role: true, cityId: true } }); const rows = await prisma.$queryRawUnsafe<any[]>(actor?.role === UserRole.SUPER_ADMIN ? 'SELECT ts.city_id "cityId",ts.slug,ts.display_name "displayName",ts.timezone,ts.default_locale "defaultLocale",ts.data_residency "dataResidency",ts.branding,c.active FROM tenant_settings ts JOIN cities c ON c.id=ts.city_id ORDER BY ts.display_name' : 'SELECT ts.city_id "cityId",ts.slug,ts.display_name "displayName",ts.timezone,ts.default_locale "defaultLocale",ts.data_residency "dataResidency",ts.branding,c.active FROM tenant_settings ts JOIN cities c ON c.id=ts.city_id WHERE ts.city_id=$1::uuid', ...(actor?.role === UserRole.SUPER_ADMIN ? [] : [actor?.cityId])); return res.json({ success: true, data: { tenants: rows } }); });
router.post('/', authenticateJWT, requireRole(superOnly), async (req: AuthenticatedRequest, res: Response) => { const cityId = typeof req.body?.cityId === 'string' ? req.body.cityId : ''; const displayName = typeof req.body?.displayName === 'string' ? req.body.displayName.trim() : ''; const slug = typeof req.body?.slug === 'string' ? req.body.slug.trim().toLowerCase() : ''; if (!cityId || displayName.length < 2 || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'City, display name, and a URL-safe slug are required.' } }); const city = await prisma.city.findUnique({ where: { id: cityId }, select: { id: true } }); if (!city) return res.status(404).json({ success: false, error: { code: 'CITY_NOT_FOUND', message: 'City does not exist.' } }); const result = await prisma.$transaction(async (tx) => { const settings = await tx.$queryRawUnsafe<any[]>('INSERT INTO tenant_settings (city_id,slug,display_name,timezone,default_locale,data_residency,branding) VALUES ($1::uuid,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT (city_id) DO UPDATE SET slug=EXCLUDED.slug,display_name=EXCLUDED.display_name,timezone=EXCLUDED.timezone,default_locale=EXCLUDED.default_locale,data_residency=EXCLUDED.data_residency,branding=EXCLUDED.branding,updated_at=NOW() RETURNING city_id "cityId",slug,"display_name" "displayName",timezone,default_locale "defaultLocale",data_residency "dataResidency",branding', cityId, slug, displayName, req.body?.timezone || 'Asia/Kolkata', req.body?.defaultLocale || 'hi-IN', req.body?.dataResidency || 'IN', JSON.stringify(req.body?.branding || {})); await tx.$executeRaw`UPDATE cities SET active=TRUE,updated_at=NOW() WHERE id=${cityId}::uuid`; await tx.$executeRaw`INSERT INTO tenant_feature_flags (city_id,key,enabled,rollout_percent,updated_by) VALUES (${cityId}::uuid,'REPORTING_ENABLED',TRUE,100,${req.user!.id}::uuid),(${cityId}::uuid,'PUBLIC_MAP_ENABLED',TRUE,100,${req.user!.id}::uuid),(${cityId}::uuid,'SOCIO_ENABLED',FALSE,0,${req.user!.id}::uuid),(${cityId}::uuid,'PREDICTIONS_ENABLED',FALSE,0,${req.user!.id}::uuid) ON CONFLICT (city_id,key) DO NOTHING`; await tx.$executeRaw`INSERT INTO tenant_provisioning_events (city_id,action,actor_id,details) VALUES (${cityId}::uuid,'PROVISIONED',${req.user!.id}::uuid,${JSON.stringify({ slug })}::jsonb)`; return settings[0]; }); return res.status(201).json({ success: true, data: { tenant: result } }); });
router.patch('/:cityId', authenticateJWT, requireRole(superOnly), async (req: AuthenticatedRequest, res: Response) => { const displayName = typeof req.body?.displayName === 'string' ? req.body.displayName.trim() : ''; const slug = typeof req.body?.slug === 'string' ? req.body.slug.trim().toLowerCase() : ''; if (displayName.length < 2 || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Display name and URL-safe slug are required.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('UPDATE tenant_settings SET slug=$1,display_name=$2,timezone=$3,default_locale=$4,data_residency=$5,branding=$6::jsonb,updated_at=NOW() WHERE city_id=$7::uuid RETURNING city_id "cityId",slug,"display_name" "displayName",timezone,default_locale "defaultLocale",data_residency "dataResidency",branding', slug, displayName, req.body?.timezone || 'Asia/Kolkata', req.body?.defaultLocale || 'hi-IN', req.body?.dataResidency || 'IN', JSON.stringify(req.body?.branding || {}), req.params.cityId); if (!rows[0]) return res.status(404).json({ success: false, error: { code: 'TENANT_NOT_FOUND', message: 'Tenant has not been provisioned.' } }); await prisma.$executeRaw`INSERT INTO tenant_provisioning_events (city_id,action,actor_id,details) VALUES (${req.params.cityId}::uuid,'SETTINGS_UPDATED',${req.user!.id}::uuid,${JSON.stringify({})}::jsonb)`; return res.json({ success: true, data: { tenant: rows[0] } }); });
router.put('/:cityId/features/:key', authenticateJWT, requireRole(superOnly), async (req: AuthenticatedRequest, res: Response) => { const key = req.params.key.toUpperCase(); const enabled = Boolean(req.body?.enabled); const rolloutPercent = Number.isFinite(Number(req.body?.rolloutPercent)) ? Math.min(100, Math.max(0, Number(req.body.rolloutPercent))) : enabled ? 100 : 0; if (!/^[A-Z][A-Z0-9_]{2,64}$/.test(key)) return res.status(400).json({ success: false, error: { code: 'INVALID_FEATURE_KEY', message: 'Feature key is invalid.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('INSERT INTO tenant_feature_flags (city_id,key,enabled,rollout_percent,updated_by) VALUES ($1::uuid,$2,$3,$4,$5::uuid) ON CONFLICT (city_id,key) DO UPDATE SET enabled=EXCLUDED.enabled,rollout_percent=EXCLUDED.rollout_percent,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING city_id "cityId",key,enabled,rollout_percent "rolloutPercent"', req.params.cityId, key, enabled, rolloutPercent, req.user!.id); if (!rows[0]) return res.status(404).json({ success: false, error: { code: 'TENANT_NOT_FOUND', message: 'Tenant not found.' } }); return res.json({ success: true, data: { feature: rows[0] } }); });
router.get('/:cityId/features', authenticateJWT, requireRole(admins), async (req: AuthenticatedRequest, res: Response) => { const actor = await prisma.user.findUnique({ where: { id: req.user!.id }, select: { role: true, cityId: true } }); if (actor?.role !== UserRole.SUPER_ADMIN && actor?.cityId !== req.params.cityId) return res.status(403).json({ success: false, error: { code: 'SCOPE_DENIED', message: 'You cannot inspect another city.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('SELECT key,enabled,rollout_percent "rolloutPercent",updated_at "updatedAt" FROM tenant_feature_flags WHERE city_id=$1::uuid ORDER BY key', req.params.cityId); return res.json({ success: true, data: { features: rows } }); });
router.put('/:cityId/policies/:domain', authenticateJWT, requireRole(superOnly), async (req: AuthenticatedRequest, res: Response) => { const domain = req.params.domain.trim().toUpperCase(); const version = typeof req.body?.version === 'string' ? req.body.version.trim() : ''; if (!/^[A-Z][A-Z0-9_]{2,50}$/.test(domain) || !/^[a-z0-9._-]{2,50}$/.test(version) || !req.body?.config || typeof req.body.config !== 'object') return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Domain, version, and JSON policy configuration are required.' } }); const result = await prisma.$transaction(async (tx) => { await tx.$executeRaw`UPDATE tenant_policy_versions SET active=FALSE WHERE city_id=${req.params.cityId}::uuid AND domain=${domain}`; const rows = await tx.$queryRawUnsafe<any[]>('INSERT INTO tenant_policy_versions (city_id,domain,version,config,active,effective_at,created_by) VALUES ($1::uuid,$2,$3,$4::jsonb,TRUE,NOW(),$5::uuid) ON CONFLICT (city_id,domain,version) DO UPDATE SET config=EXCLUDED.config,active=TRUE,effective_at=NOW(),created_by=EXCLUDED.created_by RETURNING id,city_id "cityId",domain,version,config,active,effective_at "effectiveAt"', req.params.cityId, domain, version, JSON.stringify(req.body.config), req.user!.id); await tx.$executeRaw`INSERT INTO tenant_provisioning_events (city_id,action,actor_id,details) VALUES (${req.params.cityId}::uuid,'POLICY_ACTIVATED',${req.user!.id}::uuid,${JSON.stringify({ domain, version })}::jsonb)`; return rows[0]; }); return res.status(201).json({ success: true, data: { policy: result } }); });
router.get('/:cityId/policies', authenticateJWT, requireRole(admins), async (req: AuthenticatedRequest, res: Response) => { const actor = await prisma.user.findUnique({ where: { id: req.user!.id }, select: { role: true, cityId: true } }); if (actor?.role !== UserRole.SUPER_ADMIN && actor?.cityId !== req.params.cityId) return res.status(403).json({ success: false, error: { code: 'SCOPE_DENIED', message: 'You cannot inspect another city.' } }); const rows = await prisma.$queryRawUnsafe<any[]>('SELECT id,domain,version,config,active,effective_at "effectiveAt" FROM tenant_policy_versions WHERE city_id=$1::uuid ORDER BY domain,created_at DESC', req.params.cityId); return res.json({ success: true, data: { policies: rows } }); });
router.patch('/:cityId/lifecycle', authenticateJWT, requireRole(superOnly), async (req: AuthenticatedRequest, res: Response) => { const active = Boolean(req.body?.active); const result = await prisma.$transaction(async (tx) => { const rows = await tx.$queryRawUnsafe<any[]>('UPDATE cities SET active=$1,updated_at=NOW() WHERE id=$2::uuid RETURNING id,active', active, req.params.cityId); if (!rows[0]) return null; await tx.$executeRaw`INSERT INTO tenant_provisioning_events (city_id,action,actor_id,details) VALUES (${req.params.cityId}::uuid,${active ? 'ACTIVATED' : 'DEACTIVATED'},${req.user!.id}::uuid,${JSON.stringify({ active })}::jsonb)`; return rows[0]; }); if (!result) return res.status(404).json({ success: false, error: { code: 'CITY_NOT_FOUND', message: 'City not found.' } }); return res.json({ success: true, data: { city: result } }); });

export default router;
